### ISSUE TITLE
Support for new website

### ISSUE THREAD

**Issue by matthazinski** [wuvt/mpd-automation#4]
I'm not sure if we tested this with trackman. Someone should investigate.

**Comment by telnoratti** [comment]
It should be able to easily hook into the api. Doubt it's logging tracks
now, though.

**Comment by matthazinski** [comment]
Closing, since it seems to work.

**Comment by telnoratti** [comment]
This done done in wuvt/wuvt-site@ea6d33cd3ae77995eed0dfc77e98a7a022b0a178 8b0aebd387ab3e4204a50ae8a292b64448c60ed7
